version: '3.8'
services:
  backend-app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
  db:
    image: postgres:alpine
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bangjago:/var/lib/postgresql/data

volumes:
  bangjago: