services:
  backend-app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:${APP_PORT}"
      - "9090:${APP_GRPC_PORT}"
  db:
    image: postgres:alpine
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bangjago:/var/lib/postgresql/data

volumes:
  bangjago: